# netlify.toml

[build]

  command = "npm run build:prod"
  publish = "dist/browser"  

[[redirects]]
  from = "/api/*"
  to = "https://yahoo-weather5.p.rapidapi.com/weather:splat"
  status = 200
  force = true
  headers = [
    { key = "X-RapidAPI-Host", value = ":XRapidAPIHostHeaderValue" },
    { key = "X-RapidAPI-Key", value = ":XRapidAPIKeyHeaderValue" }
  ]
  
